spring:
  application:
     name: mongo-service  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/mongo-server3-service/templates/    # Trailing / mandatory
                             # Template location for this application only
  data:
    mongodb:
      host: localhost
      port: 27019
      database: monitor
server:
  max-http-header-size: 50000

# Map the error path to error template (for Thymeleaf)
error.path: /error

# HTTP Server
server.port: 6666   # HTTP (Tomcat) port

# Discovery Server Access
#  1. DEV ONLY: Reduce the lease renewal interval to speed up registration
#  2. Define URL of registration server (defaultZone)
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

#  3. If using the Angel release-train ONLY, give the process a unique instance id 
#     so that multiple instances can register when running on SAME host.  This is
#     not needed since release-train Brixton.
#     NOTE-1: spring.application.instance_id is only set when run on Cloud Foundry,
#             so we fallback on the server-port when it is not defined
#     NOTE-2: Syntax ${x:${y}} = use $x if set, otherwise use $y
#   metadataMap:
#     instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}


# Enable actuator access without security checks - DEVELOPEMENT ONLY
# management.security.enabled: false   Spring Boot 1.5 property
management.endpoints.monitor.exposure.include: '*'


  
