/* SubHuntViewController class
*  Anderson, Franceschi
*/

import javafx.scene.layout.*;
import javafx.scene.input.*;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.stage.Stage;

public class SubHuntViewController extends VBox
{
  private SubHunt sub; // submarine
  private Stage stage;
  private GraphicsContext gc;
 
  /** Constructor
  * @param sub the Model reference for this game
  * @param stage the Stage for this game
  * @param width the width of the Canvas rendering the game
  * @param height the height of the Canvas rendering the game
  */
  public SubHuntViewController( SubHunt sub, 
                                Stage stage, int width, int height )
  {
    this.sub = sub;
    this.stage = stage;
    Canvas canvas = new Canvas( width, height );
    getChildren( ).add( canvas );
    gc = canvas.getGraphicsContext2D( );
  
    this.setOnMouseClicked( event -> handleMouseEvent( event ) );
    this.setOnTouchPressed( event -> handleTouchEvent( event ) );    
  }
 
  /** handleMouseEvent method
  * @param event the MouseEvent generated by the user
  */
  public void handleMouseEvent( MouseEvent event ) 
  {
    int x = ( int ) event.getSceneX( );
    int y = ( int ) event.getSceneY( );
    play( x, y );
  }
 
  /** handleTouchEvent method
  * @param event the TouchEvent generated by the user
  */
  public void handleTouchEvent( TouchEvent event ) 
  {
    int x = ( int ) event.getTouchPoint( ).getSceneX( );
    int y = ( int ) event.getTouchPoint( ).getSceneY( );
    play( x, y );
  }

  /** play method
  * @param x the x coordinate of the play
  * @param y the y coordinate of the play
  */
  public void play( int x, int y )
  {
    sub.play( x, y );
    sub.draw( gc, x, y );
    stage.setTitle( sub.getStatus( ) );   
    if ( sub.isHit( ) )
    {
      this.setOnMouseClicked( null );
      this.setOnTouchPressed( null ); 
    }
  }
}